### ISSUE TITLE
线程池的使用疑问，线程有正常切换，但执行完就报错了

### ISSUE THREAD

**Issue by 19chang19** [cxxjava/CxxJDK#6]
![image](https://user-images.githubusercontent.com/8297441/199726091-8a5ee789-1df6-4931-b862-a180b6e95703.png)

**Comment by cxxjava** [comment]
线程使用方法错误，请参考 https://github.com/cxxjava/CxxJDK/blob/master/test/testefc.cpp

线程池使用方法错误，请参考 https://github.com/cxxjava/CxxJDK/blob/master/test/testefc.cpp，并仔细阅读 doc/Guide.md 关于对象生命周期的说明。

**Comment by 19chang19** [comment]
现在线程使用没有问题了，我昨天把那个issues关闭了，
线程池我现在还是没有看明白哪里使用错了，其中CCarLinkWinceDlg是实现了ERunnable接口，executor是成员变量。
能帮忙指出是哪里使用错误了吗？万分感谢~

**Comment by cxxjava** [comment]
请注意到 EThreadPoolExecutor execute方法定义参数是sp类型的，virtual void execute(sp<ERunnable> command);
内部在run执行完后会自动释放command对象资源。

**Comment by 19chang19** [comment]
那 EThread* thread = new EThread((ERunnable*)this,"threada");的第一个参数也是sp ,那应该也会报错才对。
是我哪里理解错了吗？

**Comment by 19chang19** [comment]
sp<ERunnable> cmd((ERunnable*)this);
	executor->execute(cmd);
改成这样后，cmd如何将cmd有引用计数再加1呢？
