### ISSUE TITLE
大神，doc/Guid.md的eal<EString> arrList;//eal 是什么类，找不到，报错了

### ISSUE THREAD

**Issue by 19chang19** [cxxjava/CxxJDK#7]
![image](https://github.com/cxxjava/CxxJDK/assets/8297441/d5e7b223-eccd-426e-940e-53dfc81a6109)

**Comment by 19chang19** [comment]
是外部的efc.h文件里吗？，在cxxjdk里找不到efc.h

**Comment by 19chang19** [comment]
引入了Efc.hh文件，也找不到EAL类

**Comment by cxxjava** [comment]
不好意思，我搞错了，新版已经取消eal了，新用法参考 EArrayList<sp<String>> xxx



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月09日 09:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cxxjava/CxxJDK] 大神，doc/Guid.md的eal<EString> arrList;//eal 是什么类，找不到，报错了 (Issue #7) |

引入了Efc.hh文件，也找不到EAL类

**Comment by 19chang19** [comment]
好的
